version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install -e .
      - pip install sphinx sphinx-rtd-theme
      - pip install numpy pandas xarray matplotlib scipy  # if you prefer not to mock
sphinx:
  configuration: docs/source/conf.py
formats: []
